/** ko copy, `account` namespace (/account, PLAN S10). Spread into ko.ts; en mirror in account.en.ts. */
export const koAccount = {
  title: '내 계정',
  back: '홈으로',
  sub: '가입 없이 써도 돼요. 다른 기기에서도 기록을 보고 싶을 때만 로그인하세요.',
  homeLink: '내 계정',
  status: {
    title: '로그인 상태',
    loading: '계정을 확인하는 중이에요.',
    notConnected: '서버에 연결되지 않아서 계정 설정을 쓸 수 없어요.',
    error: '지금은 접속을 시작하지 못했어요. 인터넷 연결을 확인하고 다시 해 주세요.',
    errorBusy: '이 네트워크에서 방금 접속이 너무 많이 몰렸어요. 1분쯤 뒤에 다시 해 주세요.',
    retry: '다시 시도',
    anonymous: '익명 ID로 쓰는 중',
    anonymousBody:
      '기록은 이 기기의 익명 ID에만 남아요. 폰을 바꿔도 기록을 이어 보려면 로그인하세요.',
    signedIn: '로그인됨',
    signedInAs: '{email} 계정으로 로그인했어요.',
    signedInNoEmail: '이메일 없이 로그인했어요.',
    linkedTitle: '연결된 로그인 수단',
    pendingEmail: '{email} 확인을 기다리는 중이에요. 그 메일의 링크를 열어 주세요.',
  },
  methods: {
    email: '이메일',
    google: '구글',
    kakao: '카카오',
  },
  keep: {
    title: '기록 지키기',
    sub: '로그인하면 이 기기의 기록이 내 계정으로 그대로 옮겨져요. 사라지는 기록은 없어요.',
    addTitle: '로그인 수단 추가',
    addSub: '추가한 수단 어느 것으로 들어와도 같은 계정이에요.',
    allLinked: '쓸 수 있는 로그인 수단이 모두 연결돼 있어요.',
    emailLabel: '이메일',
    emailHint: '로그인 링크를 보내 드려요. 비밀번호는 없어요.',
    emailSend: '링크 보내기',
    sending: '보내는 중이에요.',
    google: '구글로 계속하기',
    kakao: '카카오로 계속하기',
    leaving: '{provider}로 이동하는 중이에요.',
    comingSoon: '준비 중',
    checking: '쓸 수 있는 로그인 수단을 확인하는 중이에요.',
  },
  existing: {
    title: '이미 계정이 있나요?',
    sub: '전에 만든 계정으로 로그인해요.',
    warning:
      '이 기기에서 익명 ID로 남긴 기록은 그 계정으로 옮겨지지 않고, 로그인하면 더 이상 볼 수 없어요. 기록을 지키려면 위의 "기록 지키기"를 쓰세요.',
    open: '기존 계정으로 로그인',
    close: '닫기',
    emailSend: '로그인 링크 보내기',
  },
  inbox: {
    title: '메일함을 확인해 주세요',
    body: '{email}로 링크를 보냈어요. 이 폰의 이 브라우저에서 열어야 로그인이 끝나요.',
    again: '다른 이메일 쓰기',
    resend: '링크 다시 보내기',
    resendWait: '{seconds}초 뒤에 다시 보낼 수 있어요.',
    resent: '다시 보냈어요.',
  },
  redirect: {
    success: '로그인했어요.',
    kept: '로그인했어요. 이 기기의 기록이 이제 내 계정에 있어요.',
    otherBrowser:
      '링크를 다른 브라우저에서 열었어요. 링크를 요청한 브라우저에서 다시 열어 주세요. 이메일을 추가하던 중이었다면 확인은 끝났고, 원래 브라우저로 돌아가면 반영돼요.',
    dismiss: '닫기',
  },
  errors: {
    identityExists:
      '이 {provider} 로그인은 이미 다른 진짜? 계정에 연결돼 있어요. 대신 그 로그인으로 들어가 주세요.',
    someProvider: '구글·카카오',
    emailExists:
      '이 이메일로 만든 계정이 이미 있어요. 그 계정으로 로그인하면 이 익명 ID의 기록은 옮겨지지 않고, 여기서 더 이상 볼 수 없어요.',
    badEmail: '이메일 주소를 확인해 주세요.',
    tooMany: '메일을 너무 많이 보냈어요. 한 시간쯤 뒤에 다시 해 주세요.',
    linkExpired: '링크가 만료됐거나 이미 쓴 링크예요. 새 링크를 보내 주세요.',
    otherBrowser: '링크를 요청한 브라우저에서 열어 주세요.',
    cancelled: '로그인을 취소했어요. 바뀐 것은 없어요.',
    providerOff: '이 로그인 수단은 아직 준비 중이에요.',
    noAccount:
      '이 이메일로 만든 계정이 없어요. 위의 "기록 지키기"에서 이메일을 넣으면 새 계정이 만들어져요.',
    generic: '로그인하지 못했어요. 다시 해 주세요.',
    signInInstead: '그 계정으로 로그인하기',
  },
  nickname: {
    title: '닉네임',
    label: '닉네임',
    hint: '20자까지. 나만 볼 수 있어요.',
    save: '닉네임 저장',
    saving: '저장하는 중이에요.',
    saved: '저장했어요.',
    empty: '한 글자 이상 적어 주세요.',
    tooLong: '20자 이하로 적어 주세요.',
    invalid: '줄바꿈 같은 특수 문자는 빼 주세요.',
    loadError: '닉네임을 불러오지 못했어요.',
    saveError: '저장하지 못했어요. 다시 해 주세요.',
  },
  language: {
    title: '언어',
  },
  signOut: {
    title: '로그아웃',
    body: '언제든 다시 로그인할 수 있어요. 로그아웃하면 이 기기에서는 새 익명 ID로 시작해요.',
    button: '로그아웃',
    busy: '로그아웃하는 중이에요.',
    done: '로그아웃했어요. 지금은 새 익명 ID로 쓰는 중이에요.',
    error: '로그아웃하지 못했어요. 다시 해 주세요.',
  },
  remove: {
    title: '계정 삭제',
    body: '계정과 그 안의 모든 것(구매, 스캔, 수정, 신고 기록과 닉네임)을 지워요. 되돌릴 수 없어요.',
    start: '계정 삭제',
    confirmTitle: '정말 지울까요?',
    confirmBody: '확인을 위해 아래 칸에 "{word}"라고 적어 주세요.',
    word: '삭제',
    inputLabel: '확인 단어',
    mismatch: '"{word}"라고 정확히 적어 주세요.',
    confirm: '모두 지우기',
    cancel: '취소',
    busy: '지우는 중이에요.',
    done: '계정과 기록을 지웠어요. 지금은 새 익명 ID로 쓰는 중이에요.',
    error: '삭제를 끝내지 못했어요. 다시 해 주세요.',
  },
};
