import type { Copy } from '../ko';

/** en copy, `account` namespace (/account, PLAN S10). Typed against ko. */
export const enAccount: Copy['account'] = {
  title: 'My account',
  back: 'Home',
  sub: 'No sign-up needed. Sign in only if you want your records on another device too.',
  homeLink: 'My account',
  status: {
    title: 'Sign-in status',
    loading: 'Checking your account.',
    notConnected: "Not connected to the server, so account settings aren't available.",
    error: "Couldn't start a session right now. Check your connection and try again.",
    errorBusy:
      'Too many sessions were started from this network just now. Wait a minute, then try again.',
    retry: 'Try again',
    anonymous: 'Using an anonymous ID',
    anonymousBody:
      'Your records are kept under the anonymous ID on this device only. Sign in to keep them if you change phones.',
    signedIn: 'Signed in',
    signedInAs: 'Signed in as {email}.',
    signedInNoEmail: 'Signed in without an email.',
    linkedTitle: 'Linked sign-in methods',
    pendingEmail: 'Waiting for you to confirm {email}. Open the link in that email.',
  },
  methods: {
    email: 'Email',
    google: 'Google',
    kakao: 'Kakao',
  },
  keep: {
    title: 'Keep your records',
    sub: "Sign in and this device's records move to your account unchanged. Nothing is lost.",
    addTitle: 'Add a sign-in method',
    addSub: 'Any method you add opens the same account.',
    allLinked: 'Every available sign-in method is already linked.',
    emailLabel: 'Email',
    emailHint: 'We send you a sign-in link. No password.',
    emailSend: 'Send link',
    sending: 'Sending.',
    google: 'Continue with Google',
    kakao: 'Continue with Kakao',
    leaving: 'Going to {provider}.',
    comingSoon: 'Coming soon',
    checking: 'Checking which sign-in methods are ready.',
  },
  existing: {
    title: 'Already have an account?',
    sub: 'Sign in to an account you made before.',
    warning:
      'Records made on this device with the anonymous ID won\'t move to that account, and you won\'t see them here after you sign in. To keep them, use "Keep your records" above instead.',
    open: 'Sign in to an existing account',
    close: 'Close',
    emailSend: 'Send sign-in link',
  },
  inbox: {
    title: 'Check your inbox',
    body: 'We sent a link to {email}. Open it on this phone, in this browser, to finish.',
    again: 'Use a different email',
    resend: 'Send the link again',
    resendWait: 'You can send it again in {seconds} seconds.',
    resent: 'Sent again.',
  },
  redirect: {
    success: 'Signed in.',
    kept: "Signed in. This device's records are now in your account.",
    otherBrowser:
      "The link was opened in a different browser. Open it in the browser where you asked for it. If you were adding an email, it's confirmed and shows up when you go back to that browser.",
    dismiss: 'Close',
  },
  errors: {
    identityExists:
      'That {provider} login is already used by another Jinjja? account. Sign in with it instead.',
    someProvider: 'Google or Kakao',
    emailExists:
      "An account with this email already exists. If you sign in to it, records from this anonymous ID won't move over, and you won't see them here anymore.",
    badEmail: 'Check the email address.',
    tooMany: 'Too many emails were sent. Try again in about an hour.',
    linkExpired: 'The link has expired or was already used. Send a new one.',
    otherBrowser: 'Open the link in the browser where you asked for it.',
    cancelled: 'Sign-in was cancelled. Nothing changed.',
    providerOff: "This sign-in method isn't ready yet.",
    noAccount:
      'No account uses this email yet. Enter it under "Keep your records" above to make one.',
    generic: "Sign-in didn't work. Try again.",
    signInInstead: 'Sign in to that account',
  },
  nickname: {
    title: 'Nickname',
    label: 'Nickname',
    hint: 'Up to 20 characters. Only you can see it.',
    save: 'Save nickname',
    saving: 'Saving.',
    saved: 'Saved.',
    empty: 'Enter at least one character.',
    tooLong: 'Use 20 characters or fewer.',
    invalid: 'Remove line breaks and other special characters.',
    loadError: "Couldn't load your nickname.",
    saveError: "Couldn't save. Try again.",
  },
  language: {
    title: 'Language',
  },
  signOut: {
    title: 'Sign out',
    body: 'You can sign back in any time. After signing out, this device starts with a new anonymous ID.',
    button: 'Sign out',
    busy: 'Signing out.',
    done: "Signed out. You're now using a new anonymous ID.",
    error: "Couldn't sign out. Try again.",
  },
  remove: {
    title: 'Delete account',
    body: "Deletes your account and everything in it: purchases, scans, corrections, reports and your nickname. This can't be undone.",
    start: 'Delete account',
    confirmTitle: 'Delete everything?',
    confirmBody: 'To confirm, type "{word}" below.',
    word: 'delete',
    inputLabel: 'Confirmation word',
    mismatch: 'Type "{word}" exactly.',
    confirm: 'Delete everything',
    cancel: 'Cancel',
    busy: 'Deleting.',
    done: "Your account and records are deleted. You're now using a new anonymous ID.",
    error: "Deletion didn't finish. Try again.",
  },
};
