import type { Copy } from '../ko';

/** en copy, `ops` namespace (/stats, /admin, /test). Typed against ko. */
export const enOps: Copy['ops'] = {
  exampleSub:
    'The numbers and products here are examples of the layout. Real records replace them once the server is connected.',
  practice: 'Practice screen — nothing is saved yet',
  practiceSub: 'Once the server is connected, this screen saves records in test mode.',
  home: 'Home',
  count: '{n}',
  people: '{n} people',
  peopleOne: '{n} person',
  pct: '{n}%',
  sec: '{n}s',
  apps: {
    coupang: 'Coupang',
    naver: 'Naver',
    mart: 'Store app',
    other: 'Other',
  },
  trust: {
    manual: 'Own search',
    app: 'App',
    same: 'Same',
  },
  gate: {
    title: 'For the team only',
    label: 'Passcode',
    submit: 'Enter',
    note: 'This is a screen only. The passcode check comes after the server is connected. For now, any value lets you in.',
    empty: 'Enter the passcode.',
  },
  stats: {
    title: 'Stats',
    period: 'Period',
    periods: { today: 'Today', d7: 'Last 7 days', d30: 'Last 30 days', all: 'All time' },
    mode: 'Mode',
    modes: { normal: 'Normal', test: 'Test', demo: 'Demo' },
    modeNote: 'Demo is left out by default.',
    filterNote: 'This is an example screen, so the numbers stay the same when filters change.',
    usage: 'Usage',
    scans: 'Scans',
    users: 'Users',
    daily: 'Scans by day',
    speed: 'Shutter to verdict',
    median: 'Median',
    p90: 'Slowest 10% (p90)',
    edits: 'Correction rate',
    editsSub:
      'Share of confirm cards where people fixed a field. This is tag-reading accuracy in the field.',
    fields: { price: 'Price', brand: 'Brand', amount: 'Size', count: 'Count' },
    match: 'Same-product match rate',
    anySame: 'Found at least one same product',
    exactCount: 'Found the same count and gave a verdict',
    verdicts: 'Verdicts',
    storeSaid: 'Times we said "buy it here"',
    storeSaidSub: 'Store-cheaper plus same-price verdicts.',
    verdictTypes: {
      NEED_STORE_PRICE: 'Asked for store price',
      STORE_CHEAPER: 'Store is cheaper',
      SAME_PRICE: 'Same price',
      ONLINE_CHEAPER: 'Online is cheaper',
      BUNDLE_ONLY: 'Only bundles or other sizes',
      NO_MATCH: 'No same product found',
    },
    reports: 'Reports',
    reportRate: 'Reports per result shown',
    notSame: 'Links marked "No" (not the same item)',
    savings: 'Potential savings',
    savingsTotal: 'Online-cheaper gaps, total',
    savingsSub: 'Sum of differences in online-cheaper verdicts. Estimate without shipping.',
    purchases: 'Purchases',
    storeConfirmed: 'Store purchases confirmed',
    onlinePlanned: 'Online purchases planned',
    converted: 'Planned turned into bought',
    reuse: 'Returning users',
    reuseSub: 'Users who scanned on 2 or more different days',
    cost: 'Cost',
    costPerScan: 'Average per scan',
    costTotal: 'Total',
    field: 'Field test',
    fieldTime: 'Time to find the same product (median)',
    fieldSuccess: 'Found the same product',
    manualSuccess: 'Own search found it',
    appFound: 'App found it',
    appsUsed: 'Apps used for own search',
    appsNote: "Coupang's share is how often people searched outside the app's current scope.",
    trustPicks: 'Trusted more',
    exportTitle: 'CSV export',
    exportButton: 'Download {table}',
    dailyChart: 'Scans per day, last 7 days',
    tables: {
      events: 'events',
      scans: 'scans',
      corrections: 'corrections',
      purchases: 'purchases',
      reports: 'reports',
      manual_trials: 'field trials',
      api_calls: 'API calls and cost',
    },
    exportNote:
      'CSV downloads work once the server is connected. This is an example, so no file is made.',
  },
  admin: {
    title: 'Admin',
    uploadTitle: 'CSV upload',
    uploadSub:
      'Rows with the same barcode are overwritten. Without a barcode, rows match on brand, name, type, size and count.',
    uploadPick: 'Choose a CSV file',
    uploadColumns: 'Required columns',
    uploadPicked: 'Chosen file: {name}',
    uploadPending: 'Upload works once the server is connected. The file was not sent.',
    productsTitle: '{n} curated products',
    productsTitleOne: '{n} curated product',
    barcode: 'Barcode {code}',
    noBarcode: 'No barcode',
    links: '{n} confirmed links',
    linksOne: '{n} confirmed link',
    search: 'Search Naver',
    hide: 'Close candidates',
    candidatesNote: 'Example candidates. Not real Naver results.',
    catalog: 'Naver price comparison (multiple sellers)',
    shippingUnknown: 'Shipping unknown',
    relations: { same_item: 'Same item', size_diff: 'Other size', wrong: 'Wrong' },
    marked: 'Marked "{relation}". Not saved yet.',
    reportsTitle: '{n} reports',
    reportsTitleOne: '{n} report',
    reportKinds: {
      wrong_product: 'Different product',
      wrong_size: 'Different size or count',
      wrong_price: 'Different price',
      other: 'Other',
    },
    reportProduct: 'Product: {label}',
    reportNote: 'Note: {note}',
    exampleNotes: { twoPackSameItem: 'The 2-pack came up as the same product' },
    recheck: 'Recheck the link',
    markWrong: 'Mark as wrong',
    handled: 'Chose "{action}". Not saved yet.',
  },
  test: {
    title: 'Field test',
    guideTitle: 'Facilitator notes',
    guide1: 'Photograph price tags only. No people, no whole shelves.',
    guide2: "Don't block the aisle.",
    guide3: "If staff ask, explain it's a student startup test and follow their lead.",
    code: 'Participant code',
    codeHint: 'e.g. H01',
    consentPhoto: 'I agree to my price tag photos being stored',
    consentGuardian: '(Minor participants) A guardian has agreed',
    guardianHint: 'Leave blank for adult participants.',
    start: 'Start the test',
    needCode: 'Enter a participant code.',
    needConsent: 'Photo storage consent is needed to start.',
    participant: 'Participant {code}',
    productsTitle: 'Products',
    productsSub: 'The facilitator writes product names on the spot. Up to {max}.',
    productName: 'Product name',
    productPlaceholder: 'e.g. Downy indoor dry 2.6L',
    add: 'Add',
    full: 'All {max} slots are used.',
    empty: 'No products yet. Write a name above to add one.',
    orderNote: 'Odd-numbered products start with own search, even-numbered ones with the app.',
    position: 'No. {n}',
    manualFirst: 'Own search first',
    appFirst: 'App first',
    open: 'Run',
    finished: 'Done',
    toSurvey: 'Go to final questions',
    step: 'Step {n} of 2',
    manualTitle: 'Own search',
    manualSub: 'The participant finds the same product in the shopping app they usually use.',
    timerStart: 'Start',
    elapsed: 'Elapsed',
    found: 'Found the same product',
    unsure: 'Not sure',
    gaveUp: 'Gave up',
    outcome: 'Result: {outcome}',
    foundPrice: 'Price found (₩)',
    appUsed: 'App used',
    appTitle: 'Scan with the app',
    appSub:
      'Runs the normal scan flow in test mode. Only tag photos from participants who agreed are stored.',
    appPending: "Test-mode scanning isn't connected yet. You can move on for now.",
    appDone: 'Saw the app result',
    trustTitle: 'Which result do you trust more?',
    next: 'Next',
    backToList: 'Back to list',
    surveyTitle: 'Three final questions',
    q1: 'Which screen was most confusing?',
    q2: 'Would you use it on your next shopping trip?',
    q2Scale: '1 means probably not, 5 means definitely.',
    q3: 'Which item do you most want to check?',
    submit: 'Submit',
    thanks: 'Thank you. The test is done.',
    restart: 'Start over',
  },
};
