/** ko copy, `ops` namespace (/stats, /admin, /test). Spread into ko.ts; en mirror in ops.en.ts. */
export const koOps = {
  exampleSub:
    '숫자와 상품은 화면 모양을 보여 주려고 넣은 예시예요. 서버에 연결되면 실제 기록으로 바뀌어요.',
  practice: '연습 화면 — 아직 아무것도 저장되지 않아요',
  practiceSub: '서버에 연결되면 이 화면의 기록이 실험 모드로 저장돼요.',
  home: '홈으로',
  count: '{n}건',
  people: '{n}명',
  peopleOne: '{n}명',
  pct: '{n}%',
  sec: '{n}초',
  apps: {
    coupang: '쿠팡',
    naver: '네이버',
    mart: '마트 앱',
    other: '기타',
  },
  trust: {
    manual: '직접 검색',
    app: '앱',
    same: '같아요',
  },
  gate: {
    title: '운영자만 볼 수 있어요',
    label: '패스코드',
    submit: '들어가기',
    note: '지금은 화면만 있어요. 패스코드 확인은 서버를 연결한 뒤에 붙여요. 지금은 아무 값이나 넣으면 들어가요.',
    empty: '패스코드를 입력해 주세요.',
  },
  stats: {
    title: '지표',
    period: '기간',
    periods: { today: '오늘', d7: '최근 7일', d30: '최근 30일', all: '전체' },
    mode: '모드',
    modes: { normal: '일반', test: '실험', demo: '데모' },
    modeNote: '데모는 기본으로 빠져 있어요.',
    filterNote: '예시 화면이라 필터를 바꿔도 숫자는 그대로예요.',
    usage: '사용',
    scans: '스캔 수',
    users: '사용자 수',
    daily: '날짜별 스캔',
    speed: '셔터에서 판정까지',
    median: '중앙값',
    p90: '느린 쪽 10% 경계(p90)',
    edits: '인식 수정률',
    editsSub: '확인 카드에서 사용자가 고친 비율이에요. 현장에서 본 가격표 읽기 정확도예요.',
    fields: { price: '가격', brand: '브랜드', amount: '용량', count: '수량' },
    match: '같은 상품 발견율',
    anySame: '같은 상품을 1개 이상 찾음',
    exactCount: '같은 수량까지 찾아 판정함',
    verdicts: '판정 분포',
    storeSaid: '"마트에서 사세요"라고 말한 횟수',
    storeSaidSub: '마트가 싼 판정과 가격이 같은 판정을 더한 값이에요.',
    verdictTypes: {
      NEED_STORE_PRICE: '매장가 입력 요청',
      STORE_CHEAPER: '마트가 싸요',
      SAME_PRICE: '가격이 같아요',
      ONLINE_CHEAPER: '온라인이 싸요',
      BUNDLE_ONLY: '묶음이나 다른 용량만 있어요',
      NO_MATCH: '같은 상품을 못 찾았어요',
    },
    reports: '신고',
    reportRate: '결과 화면 대비 신고율',
    notSame: '링크 피드백 중 "아니에요"',
    savings: '잠재 절약액',
    savingsTotal: '온라인이 싼 차액 합계',
    savingsSub: '온라인이 싸다고 판정한 차액의 합계예요. 배송비 미반영 추정이에요.',
    purchases: '구매 확인',
    storeConfirmed: '마트 구매 확인',
    onlinePlanned: '온라인 구매 예정',
    converted: '예정에서 구매로 바뀜',
    reuse: '재사용',
    reuseSub: '서로 다른 2일 이상 스캔한 사용자 비율',
    cost: '비용',
    costPerScan: '스캔당 평균',
    costTotal: '누적',
    field: '현장 실험',
    fieldTime: '같은 상품 찾는 시간(중앙값)',
    fieldSuccess: '같은 상품을 찾은 비율',
    manualSuccess: '직접 검색으로 찾음',
    appFound: '앱이 같은 상품을 찾음',
    appsUsed: '직접 검색에 쓴 앱',
    appsNote: '쿠팡 비중은 지금 앱의 조회 범위 밖에서 찾은 비율이에요.',
    trustPicks: '더 믿은 쪽',
    exportTitle: 'CSV 내보내기',
    exportButton: '{table} 내려받기',
    dailyChart: '최근 7일 날짜별 스캔 수',
    tables: {
      events: '이벤트',
      scans: '스캔',
      corrections: '수정 기록',
      purchases: '구매',
      reports: '신고',
      manual_trials: '현장 실험',
      api_calls: 'API 호출과 비용',
    },
    exportNote:
      'CSV는 서버를 연결한 뒤에 내려받을 수 있어요. 지금은 예시라서 파일을 만들지 않아요.',
  },
  admin: {
    title: '관리자',
    uploadTitle: 'CSV 업로드',
    uploadSub:
      '바코드가 같으면 덮어써요. 바코드가 없으면 브랜드, 제품명, 종류, 용량, 수량이 모두 같을 때 덮어써요.',
    uploadPick: 'CSV 파일 고르기',
    uploadColumns: '필요한 열',
    uploadPicked: '고른 파일: {name}',
    uploadPending: '업로드는 서버를 연결한 뒤에 돼요. 지금은 파일을 보내지 않았어요.',
    productsTitle: '큐레이션 상품 {n}개',
    productsTitleOne: '큐레이션 상품 {n}개',
    barcode: '바코드 {code}',
    noBarcode: '바코드 없음',
    links: '확인된 연결 {n}개',
    linksOne: '확인된 연결 {n}개',
    search: '네이버 조회',
    hide: '후보 닫기',
    candidatesNote: '예시 후보예요. 실제 네이버 조회 결과가 아니에요.',
    catalog: '네이버 가격비교(여러 판매처)',
    shippingUnknown: '배송비 미확인',
    relations: { same_item: '같은 상품', size_diff: '다른 용량', wrong: '틀림' },
    marked: '"{relation}"으로 골랐어요. 아직 저장되지 않아요.',
    reportsTitle: '신고 {n}건',
    reportsTitleOne: '신고 {n}건',
    reportKinds: {
      wrong_product: '다른 상품',
      wrong_size: '용량이나 수량이 다름',
      wrong_price: '가격이 다름',
      other: '기타',
    },
    reportProduct: '상품: {label}',
    reportNote: '메모: {note}',
    exampleNotes: { twoPackSameItem: '2개 묶음이 같은 상품으로 나왔어요' },
    recheck: '연결 다시 확인',
    markWrong: '틀림으로 처리',
    handled: '"{action}"을 골랐어요. 아직 저장되지 않아요.',
  },
  test: {
    title: '현장 테스트',
    guideTitle: '진행자 안내',
    guide1: '가격표만 찍어요. 사람이나 진열대 전체는 찍지 않아요.',
    guide2: '통로를 막지 않아요.',
    guide3: '직원이 물으면 학생 창업 프로젝트 테스트라고 설명하고, 요청에 따라요.',
    code: '참가 코드',
    codeHint: '예: H01',
    consentPhoto: '가격표 사진이 저장되는 것에 동의해요',
    consentGuardian: '(미성년 참가자) 보호자가 동의했어요',
    guardianHint: '성인 참가자는 비워 두세요.',
    start: '테스트 시작',
    needCode: '참가 코드를 입력해 주세요.',
    needConsent: '사진 저장에 동의해야 시작할 수 있어요.',
    participant: '참가자 {code}',
    productsTitle: '상품 목록',
    productsSub: '진행자가 그 자리에서 상품 이름을 적어요. 최대 {max}개까지예요.',
    productName: '상품 이름',
    productPlaceholder: '예: 다우니 실내건조 2.6L',
    add: '추가',
    full: '{max}개를 다 채웠어요.',
    empty: '아직 상품이 없어요. 위에서 이름을 적어 추가하세요.',
    orderNote: '홀수 번째 상품은 직접 검색 먼저, 짝수 번째는 앱 먼저 해요.',
    position: '{n}번',
    manualFirst: '직접 검색 먼저',
    appFirst: '앱 먼저',
    open: '진행하기',
    finished: '끝남',
    toSurvey: '마지막 질문으로',
    step: '{n}/2 단계',
    manualTitle: '직접 검색',
    manualSub: '참가자가 평소 쓰는 쇼핑 앱으로 같은 상품을 찾아요.',
    timerStart: '시작',
    elapsed: '지난 시간',
    found: '같은 상품 찾음',
    unsure: '애매함',
    gaveUp: '포기',
    outcome: '결과: {outcome}',
    foundPrice: '찾은 가격(원)',
    appUsed: '쓴 앱',
    appTitle: '앱으로 찍기',
    appSub: '일반 촬영 흐름을 실험 모드로 실행해요. 동의한 참가자의 가격표 사진만 저장돼요.',
    appPending: '실험 모드 촬영은 아직 연결하지 않았어요. 지금은 다음으로 넘어갈 수 있어요.',
    appDone: '앱 결과를 봤어요',
    trustTitle: '어느 쪽 결과를 더 믿어요?',
    next: '다음',
    backToList: '목록으로',
    surveyTitle: '마지막 질문 3개',
    q1: '가장 헷갈렸던 화면은 어디였어요?',
    q2: '다음 장보기에도 쓸 것 같아요?',
    q2Scale: '1은 안 쓸 것 같아요, 5는 꼭 쓸래요예요.',
    q3: '가장 확인하고 싶은 품목은 뭐예요?',
    submit: '제출',
    thanks: '고마워요. 테스트가 끝났어요.',
    restart: '처음부터',
  },
} as const;
