import type { Copy } from './ko';

/** English mirror of ko.ts. The `Copy` type rejects missing or extra keys. */
export const en: Copy = {
  app: {
    name: 'Jinjja?',
    tagline: 'Snap a store price tag and compare it with the same product online.',
  },
  home: {
    cta: 'Scan a price tag',
    manualEntry: 'Enter by hand',
    aboutLink: 'About',
  },
  capture: {
    hint: 'Fill the frame with the price tag and avoid glare.',
    retake: 'Retake',
    reading: 'Reading the price tag.',
  },
  store: {
    title: "Today's store",
    optional: 'Optional.',
    selected: 'Selected',
    otherLabel: 'Other store name',
    otherPlaceholder: 'Enter the store name',
    names: {
      emart: 'E-Mart',
      homeplus: 'Homeplus',
      lottemart: 'Lotte Mart',
      megamart: 'Mega Mart',
      nobrand: 'No Brand',
      hanaro: 'Hanaro Mart',
      other: 'Other',
    },
  },
  confirm: {
    title: 'Is this the product?',
    manualTitle: 'Enter by hand',
    check: 'Please check',
    cta: 'Yes, compare',
    saving: 'Saving.',
    back: 'Home',
    unread: 'Not read',
    verified: 'Verified product',
    verifiedSub: 'The barcode matches a registered product, so we filled in its verified size.',
    suggestions: 'Is it one of these?',
    suggestionsSub: "Tap one to fill in that product's size.",
    packagePhoto: 'This is a package photo. Enter the store price.',
    multipleTags: 'Several tags were visible, so we read the largest one in the center.',
    notes: 'Reading note: {notes}',
    required: 'Required. Please fill this in.',
    invalidNumber: 'Numbers only.',
    eaAmountOptional: 'For items sold by count, you can leave the size empty.',
    unitPriceWarning:
      'This is {pct}% off the unit price printed on the tag. Check the size and count.',
    noSession: 'No price tag yet. Scan one or enter it by hand.',
    fields: {
      brand: 'Brand',
      productName: 'Product name',
      variant: 'Type (scent, flavor)',
      perItemAmount: 'Size per item',
      perItemUnit: 'Unit',
      itemCount: 'Count',
      storePrice: 'Store price (KRW)',
      promoType: 'Deal',
      promoText: 'Deal details',
      promoN: 'Buy',
      promoM: 'Get free',
    },
    optional: 'Optional',
    unitPlaceholder: 'Choose a unit',
    units: {
      ml: 'ml',
      g: 'g',
      m: 'm',
      sheet: 'sheets',
      ea: 'pcs',
    },
    promoTypes: {
      none: 'No deal',
      n_plus_m: 'Buy N get M free (1+1, 2+1)',
      percent_off: 'Percent off',
      card_discount: 'Card discount',
      multi_buy: 'Multi-buy discount',
      other: 'Other deal',
    },
    size: '{amount}{unit} × {count}',
    sizeCountOnly: '{count} pcs',
    price: '₩{price}',
  },
  next: {
    title: 'Got it',
    body: "We're still building the online price comparison for the next step. No online prices have been checked yet.",
    storeLine: 'Store: {store}',
    priceLine: 'Store price: ₩{price}',
    noStore: 'No store chosen',
    edit: 'Edit again',
    home: 'Start over',
  },
  error: {
    unreadable: "Couldn't read the tag. Fill the frame with the tag and try again.",
    network: 'Weak connection. Try again or enter it by hand.',
    notConnected:
      "Not connected to the server, so the tag can't be read. You can enter it by hand.",
    auth: "Anonymous sign-in failed, so the tag can't be read. Refresh or enter it by hand.",
    rateLimited: "You've hit the hourly scan limit. Try again later or enter it by hand.",
    tooLarge: 'The photo is too large. Please take it again.',
    image: "Couldn't open the photo. Please take it again.",
    server: 'The server hit an error while reading the tag. Retake or enter it by hand.',
  },
  commission: "This app doesn't earn commission from any seller right now.",
  version: 'v{version}',
  about: {
    title: 'About',
    back: 'Home',
    connection: 'Connection',
    latency: {
      title: 'Shutter → confirm card (this device, for testing)',
      median: 'Median of last {n}: {ms} ms',
      last: 'Last: {ms} ms',
      none: 'Nothing recorded yet. Scan a price tag to add one.',
    },
  },
  auth: {
    loading: 'Connecting.',
    notConnected: 'Not connected to the server.',
    signedIn: 'Connected with an anonymous ID.',
    userId: 'Anonymous ID: {id}',
    error: 'Anonymous sign-in failed. Refresh the page.',
    noUser: 'The server did not return an anonymous ID.',
    errorDetail: 'Error detail: {message}',
  },
};
