/** 모든 UI 문구(ko). 키를 추가하면 en.ts에도 같은 키를 넣는다 — 타입이 강제한다. */
export const ko = {
  app: {
    name: '진짜?',
    tagline: '마트 가격표를 찍으면 온라인의 같은 상품과 비교해요.',
  },
  home: {
    cta: '가격표 찍기',
    manualEntry: '직접 입력',
    aboutLink: '안내',
  },
  capture: {
    hint: '가격표가 화면을 꽉 채우게, 반사 없이 찍어 주세요.',
    retake: '다시 찍기',
    reading: '가격표를 읽는 중이에요.',
  },
  store: {
    title: '오늘의 매장',
    optional: '고르지 않아도 돼요.',
    selected: '선택됨',
    otherLabel: '기타 매장 이름',
    otherPlaceholder: '매장 이름을 입력하세요',
    names: {
      emart: '이마트',
      homeplus: '홈플러스',
      lottemart: '롯데마트',
      megamart: '메가마트',
      nobrand: '노브랜드',
      hanaro: '하나로마트',
      other: '기타',
    },
  },
  confirm: {
    title: '이 상품 맞아요?',
    manualTitle: '직접 입력',
    check: '확인해 주세요',
    cta: '맞아요, 비교하기',
    saving: '저장하는 중이에요.',
    back: '홈으로',
    unread: '미확인',
    verified: '확인된 상품',
    verifiedSub: '바코드가 등록된 상품과 일치해서 확인된 규격으로 채웠어요.',
    suggestions: '혹시 이 상품?',
    suggestionsSub: '누르면 그 상품의 규격으로 채워요.',
    packagePhoto: '상품 포장 사진이에요. 매장가를 입력해 주세요.',
    multipleTags: '가격표가 여러 개 보여서 가운데의 가장 큰 가격표를 읽었어요.',
    notes: '읽으면서 남긴 메모: {notes}',
    required: '필수 항목이에요. 입력해 주세요.',
    invalidNumber: '숫자로만 입력해 주세요.',
    eaAmountOptional: '개수로만 세는 상품은 개당 용량을 비워 둬도 돼요.',
    unitPriceWarning: '가격표에 적힌 단위가격과 {pct}% 달라요. 개당 용량과 수량을 확인해 주세요.',
    noSession: '찍은 가격표가 없어요. 가격표를 찍거나 직접 입력하세요.',
    fields: {
      brand: '브랜드',
      productName: '제품명',
      variant: '종류(향·맛 등)',
      perItemAmount: '개당 용량',
      perItemUnit: '단위',
      itemCount: '수량',
      storePrice: '매장가(원)',
      promoType: '행사',
      promoText: '행사 내용',
      promoN: '살 때 개수',
      promoM: '더 주는 개수',
    },
    optional: '선택',
    unitPlaceholder: '단위 고르기',
    units: {
      ml: 'ml',
      g: 'g',
      m: 'm',
      sheet: '매',
      ea: '개',
    },
    promoTypes: {
      none: '행사 없음',
      n_plus_m: '1+1·2+1 같은 덤 행사',
      percent_off: '할인율 행사',
      card_discount: '카드 할인',
      multi_buy: '여러 개 사면 할인',
      other: '기타 행사',
    },
    size: '{amount}{unit} {count}개',
    sizeCountOnly: '{count}개',
    price: '{price}원',
  },
  next: {
    title: '확인했어요',
    body: '온라인 가격 비교는 다음 단계에서 만들고 있어요. 아직 온라인 가격을 조회하지 않았어요.',
    storeLine: '매장: {store}',
    priceLine: '매장가: {price}원',
    noStore: '매장 미선택',
    edit: '다시 고치기',
    home: '처음으로',
  },
  error: {
    unreadable: '가격표를 읽지 못했어요. 가격표가 화면을 꽉 채우게 다시 찍어 주세요.',
    network: '연결이 약해요. 다시 시도하거나 직접 입력하세요.',
    notConnected: '서버에 연결되지 않아 가격표를 읽을 수 없어요. 직접 입력할 수 있어요.',
    auth: '익명 로그인이 되지 않아 가격표를 읽을 수 없어요. 새로고침하거나 직접 입력하세요.',
    rateLimited: '한 시간에 찍을 수 있는 횟수를 넘었어요. 잠시 후 다시 찍거나 직접 입력하세요.',
    tooLarge: '사진 용량이 너무 커요. 다시 찍어 주세요.',
    image: '사진을 열지 못했어요. 다시 찍어 주세요.',
    server: '가격표를 읽는 중에 서버 오류가 났어요. 다시 찍거나 직접 입력하세요.',
  },
  commission: '이 앱은 지금 어떤 판매처에서도 수수료를 받지 않아요.',
  version: 'v{version}',
  about: {
    title: '안내',
    back: '홈으로',
    connection: '연결 상태',
    latency: {
      title: '셔터→확인 카드 시간 (이 기기, 측정용)',
      median: '최근 {n}회 중앙값 {ms}ms',
      last: '마지막 {ms}ms',
      none: '아직 기록이 없어요. 가격표를 찍으면 쌓여요.',
    },
  },
  auth: {
    loading: '연결하는 중이에요.',
    notConnected: '서버에 연결되지 않았어요.',
    signedIn: '익명 ID로 연결됐어요.',
    userId: '익명 ID: {id}',
    error: '익명 로그인에 실패했어요. 새로고침해 주세요.',
    noUser: '서버가 익명 ID를 돌려주지 않았어요.',
    errorDetail: '오류 내용: {message}',
  },
} as const;

type Widen<T> = { [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };
export type Copy = Widen<typeof ko>;
